/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lktt;

import lktt.po.LoginPage;
import lktt.po.MainListPage;
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test(enabled = false)
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        assertTrue(false);
    }

    @Test(enabled = true)
    public void sendEmail() {
        // open mail.ru
        LoginPage loginPage = new LoginPage(true);
        // do login
        MainListPage mlPage = loginPage.login("lkktt10072020", "Qwerty1122@"); // TODO: сделать конфиг профайла запуска,
                                                                            // перенести туда данные по логину
        // send an e-mail
        mlPage.sendLetter("fake@mail.ru", "hello", "It's me");

        // check nothing
        assertTrue(true);
    }
}
